---
title: "lineage heatmaps"
output: html_notebook
---

#Set working directory to appropriate folder for inputs and outputs on Google Drive
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = '/Volumes/GoogleDrive/My Drive/Fasse_Shared/AJF_Drive_copy/Experiments/AJF009') # for aria's computer
#knitr::opts_knit$set(root.dir = '/Volumes/GoogleDrive/.shortcut-targets-by-id/1zSqx3IzXMwt6clUjwyqmlOf4G1K53lvy/Fasse_Shared/AJF_Drive_copy/Experiments/AJF009') # for dylan's computer

#2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/ is additional path for outputs

```

#Initialize
```{r include = FALSE}

# Initialize
rm(list = ls())
gc()
`%nin%` = Negate(`%in%`)
library(RColorBrewer)

# Load in the linage data
load('2022_01_14_analysis_scripts/2022_05_27_analysis/Preprocess_gDNA/preprocessed_gDNA.RData') # new gDNA data
load('2022_01_14_analysis_scripts/2022_05_27_analysis/Filtering_gDNA/filtered_gDNA.RData') #filtered matrix and lineage lists

```

#Heatplot of resistant lineages
```{r}
# heatmap based on prevalence in filtered whitelist sample, colored by prevalence in first drug state

#set order of matrix based on descending lineage size in first sample 
filtered_matrix <- filtered_matrix[order(-filtered_matrix$FirstSample),]

#make matrix of the correct dimensions, add names to row and columns
first_sorted <- matrix(0, length(filtered_matrix$Cis), 4)
colnames(first_sorted) <- c('pretreatment', 'dabtram', 'cis', 'cocl2')
rownames(first_sorted) <- rownames(filtered_matrix)

#fill each matrix column, matching the rownames, with the RPM for that lineage 
first_sorted[rownames(filtered_matrix),'pretreatment'] <- filtered_matrix$FirstSample
first_sorted[rownames(filtered_matrix), 'dabtram'] <- filtered_matrix$DabTram
first_sorted[rownames(filtered_matrix), 'cis'] <- filtered_matrix$Cis
first_sorted[rownames(filtered_matrix), 'cocl2'] <- filtered_matrix$CoCl2

#plot a log scaled version of all lineages, removing NA values, that have reads for at least one condition (rowsum > 0)
pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/firstsorted_full.pdf', height = 10, width = 10)
heatmap(log(first_sorted[rowSums(first_sorted, na.rm = TRUE) > 0,]+1), scale = "none", Colv = NA, Rowv = NA, col= brewer.pal(n = 9, name = 'OrRd'),
        ylab = paste0('n=', 0.25*(length(first_sorted[rowSums(first_sorted, na.rm = TRUE) > 0]))))
dev.off()

#same plot but just for the 1000 top entries in matrix (biggest in first drug state)
pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/firstsorted_1000.pdf', height = 10, width = 10)
heatmap(head(log(first_sorted[rowSums(first_sorted, na.rm = TRUE) > 0,]+1), 1000), scale = "none", Colv = NA, Rowv = NA, col = brewer.pal(n = 9, name = 'OrRd'),
        ylab = paste0('n=', 1000))
dev.off()
```

```{r}
# heatmap based on prevalence in dabtram sample, colored by prevalence in end drug state

filtered_matrix <- filtered_matrix[order(-filtered_matrix$DabTram),]

dabtram_sorted <- matrix(0, length(filtered_matrix$DabTram), 4)
colnames(dabtram_sorted) <- c('dabtram', 'dabtramtodabtram', 'dabtramtocis', 'dabtramtococl2')
rownames(dabtram_sorted) <- rownames(filtered_matrix)

dabtram_sorted[rownames(filtered_matrix),'dabtram'] <- filtered_matrix$DabTram
dabtram_sorted[rownames(filtered_matrix), 'dabtramtodabtram'] <- filtered_matrix$DabTramtoDabTram
dabtram_sorted[rownames(filtered_matrix), 'dabtramtocis'] <- filtered_matrix$DabTramtoCis
dabtram_sorted[rownames(filtered_matrix), 'dabtramtococl2'] <- filtered_matrix$DabTramtoCoCl2

pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/dabtramsorted_full.pdf', height = 10, width = 10)
heatmap(log(dabtram_sorted[rowSums(dabtram_sorted, na.rm = TRUE) > 0,]+1), scale = "none", Colv = NA, Rowv = NA, col= brewer.pal(n = 9, name = 'OrRd'), 
        ylab = paste0('n=', 0.25*(length(dabtram_sorted[rowSums(dabtram_sorted, na.rm = TRUE) > 0]))))
dev.off()

pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/dabtramsorted_1000.pdf', height = 10, width = 10)
heatmap(head(log(dabtram_sorted[rowSums(dabtram_sorted, na.rm = TRUE) > 0,]+1), 1000), scale = "none", Colv = NA, Rowv = NA, col = brewer.pal(n = 9, name = 'OrRd'), 
        ylab = paste0('n=', 1000))
dev.off()

pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/dabtramsorted_50.pdf', height = 10, width = 10)
heatmap(head(log(dabtram_sorted[rowSums(dabtram_sorted, na.rm = TRUE) > 0,]+1), 50), scale = "none", Colv = NA, Rowv = NA, col = brewer.pal(n = 9, name = 'OrRd'),
        ylab = paste0('n=', 50))
dev.off()
```

```{r}
# heatmap based on prevalence in cocl2 sample, colored by prevalence in end drug state

filtered_matrix <- filtered_matrix[order(-filtered_matrix$CoCl2),]

cocl2_sorted <- matrix(0, length(filtered_matrix$CoCl2), 4)
colnames(cocl2_sorted) <- c('cocl2', 'cocl2tococl2', 'cocl2tocis', 'cocl2todabtram')
rownames(cocl2_sorted) <- rownames(filtered_matrix)

cocl2_sorted[rownames(filtered_matrix),'cocl2'] <- filtered_matrix$CoCl2
cocl2_sorted[rownames(filtered_matrix), 'cocl2tococl2'] <- filtered_matrix$CoCl2toCoCl2
cocl2_sorted[rownames(filtered_matrix), 'cocl2tocis'] <- filtered_matrix$CoCl2toCis
cocl2_sorted[rownames(filtered_matrix), 'cocl2todabtram'] <- filtered_matrix$CoCl2toDabTram

pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/cocl2sorted_full.pdf', height = 10, width = 10)
heatmap(log(cocl2_sorted[rowSums(cocl2_sorted, na.rm = TRUE) > 0,]+1), scale = "none", Colv = NA, Rowv = NA, col= brewer.pal(n = 9, name = 'OrRd'), 
        ylab = paste0('n=', 0.25*(length(cocl2_sorted[rowSums(cocl2_sorted, na.rm = TRUE) > 0]))))
dev.off()

pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/cocl2sorted_1000.pdf', height = 10, width = 10)
heatmap(head(log(cocl2_sorted[rowSums(cocl2_sorted, na.rm = TRUE) > 0,]+1), 1000), scale = "none", Colv = NA, Rowv = NA, col = brewer.pal(n = 9, name = 'OrRd'), 
        ylab = paste0('n=', 1000))
dev.off()

pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/cocl2sorted_50.pdf', height = 10, width = 10)
heatmap(head(log(cocl2_sorted[rowSums(cocl2_sorted, na.rm = TRUE) > 0,]+1), 50), scale = "none", Colv = NA, Rowv = NA, col = brewer.pal(n = 9, name = 'OrRd'),
        ylab = paste0('n=', 50))
dev.off()
```


```{r}
# heatmap based on prevalence in cocl2 sample, colored by prevalence in end drug state

filtered_matrix <- filtered_matrix[order(-filtered_matrix$Cis),]

cis_sorted <- matrix(0, length(filtered_matrix$Cis), 4)
colnames(cis_sorted) <- c('cis', 'cistocis', 'cistococl2', 'cistodabtram')
rownames(cis_sorted) <- rownames(filtered_matrix)

cis_sorted[rownames(filtered_matrix),'cis'] <- filtered_matrix$Cis
cis_sorted[rownames(filtered_matrix), 'cistocis'] <- filtered_matrix$CistoCis
cis_sorted[rownames(filtered_matrix), 'cistococl2'] <- filtered_matrix$CistoCoCl2
cis_sorted[rownames(filtered_matrix), 'cistodabtram'] <- filtered_matrix$CistoDabTram

pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/cissorted_full.pdf', height = 10, width = 10)
heatmap(log(cis_sorted[rowSums(cis_sorted, na.rm = TRUE) > 0,]+1), scale = "none", Colv = NA, Rowv = NA, col= brewer.pal(n = 9, name = 'OrRd'), 
        ylab = paste0('n=', 0.25*(length(cis_sorted[rowSums(cis_sorted, na.rm = TRUE) > 0]))))
dev.off()

pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/cissorted_1000.pdf', height = 10, width = 10)
heatmap(head(log(cis_sorted[rowSums(cis_sorted, na.rm = TRUE) > 0,]+1), 1000), scale = "none", Colv = NA, Rowv = NA, col = brewer.pal(n = 9, name = 'OrRd'), 
        ylab = paste0('n=', 1000))
dev.off()

pdf('2022_01_14_analysis_scripts/2022_05_27_analysis/Lineage_heatmaps/cissorted_50.pdf', height = 10, width = 10)
heatmap(head(log(cis_sorted[rowSums(cis_sorted, na.rm = TRUE) > 0,]+1), 50), scale = "none", Colv = NA, Rowv = NA, col = brewer.pal(n = 9, name = 'OrRd'),
        ylab = paste0('n=', 50))
dev.off()

```